spring.application.name=airline
server.port=8081

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/airline_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=aayush
spring.datasource.password=aayush@1

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

error.flight.notfound=No flight found with the specified ID.
error.flight.alreadyexists=Flight with this flight number already exists.
error.admin.notfound=Admin account not found with the provided email.
error.admin.invalidcredentials=Invalid email or password.
